
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: deploy_mysql_development_sherpa

test:
  <<: *default
  database: deploy_mysql_test_sherpa

production:
  adapter: mysql2
  database: deploy_mysql_production_sherpa
